### ISSUE TITLE
Suggestion: Move away from background jobs

### ISSUE THREAD

**Issue by fatkodima** [drivy/checker_jobs#127]
Love the gem! Almost half of the projects I worked with, implemented something similar internally.

From your readme:
> At the moment, only Sidekiq is supported as a job processor to asynchronously check for data inconsitencies. The gem is designed to supports more processor. PRs are appreciated

What do you think about implementing only checks related logic in this gem and do not bother yourself with background processing?

So what I propose is something like:
1. user can define their checks logic
```ruby
class UserChecks
  include CheckerJobs::Base

  notify :email, to: "oss@drivy.com"

  ensure_no :user_without_email do
    UserRepository.missing_email.size
  end

  ensure_no :something_else ...
end
```

2. and then he can call it however he likes: 

In rake tasks
```ruby
task user_checks => :environment do
  UserChecks.perform_all # or something like this
end
```

or in background jobs (Active Job)
```ruby
class UserChecksJob < ActiveJob::Base
  queue_as :slow # activejob specific configuration

  rescue_from(ActiveRecord::RecordNotFound) do |exception|  # activejob specific configuration
    # Do something with the exception
  end
  
  def perform
    UserChecks.perform_all
  end
end
```

or Sidekiq, for example:
```ruby
class UserChecksWorker
  include Sidekiq::Worker

  sidekiq_options queue: :critical, retry: 5, backtrace: true # sidekiq specific configuration

  sidekiq_retry_in do |count, exception|  # sidekiq specific configuration
    case exception
    when SpecialException
      10 * (count + 1) # (i.e. 10, 20, 30, 40, 50)
    end
  end

  def perform
    UserChecks.perform_all
  end
end
```

This will simplify the gem by removing background processing logic and the need of implementing support for other processors; user can use any background processor he likes and customize it for his specific needs and use all it's available features, without invention of processor-specific customization options (like `options sidekiq: { queue: :slow }` right now)

**Comment by nicoolas25** [comment]
Hi @fatkodima thank you very much for the idea and for the support. Thank you for your patience as well as you suggested this a couple of months ago.

I totally agree with you that the processing parts could be put in another gem. It doesn't bring as much value here as it brings constraints. This part was very specific to the codebase this gem was extracted from. I'm gonna keep in mind the split in separate gems for the future. If you're interested to contribute to this effort, let me know!

I think adding a basic `:inline` processor could limit the negative impact of this choice without impacting the current users. This new processor would become the default one. It would simply process the various checks sequentially, providing the `.perform_all` method. This would leave the door open for more customized integrations.

Are you using `checker_jobs` yourself? What do you think? Would that help?
